export default {
  ADD_BUTTON                 : 'Add',
  DOCUMENT_TITLE             : 'Accounting Service',
  DOCUMENT_TITLE_HOME        : 'Main page',
  DOCUMENT_TITLE_DETAILS     : 'Details page',
  DOCUMENT_TITLE_NOT_FOUND   : 'Not Found',
  NOT_FOUND                  : '404 Page not Found',
  YES                        : 'Yes',
  NO                         : 'No',
  CANCEL                     : 'Cancel',
  DATE                       : 'Date',
  TIME                       : 'Time',
  TOTAL                      : 'Total',
  TYPE                       : 'Operation type',
  PAYMENT                    : 'Payment',
  CONFIRM_DELETE             : 'Are you sure you want to delete?',
  ACTIONS                    : 'Actions',
  SELECT_YEAR                : 'Select year',
  SELECT_MONTH               : 'Select month',
  INPUT_PAYMENT              : 'Input payment',
  ADD_PAYMENT                : 'Add payment',
  MODAL_ADD_PAYMENT          : 'Make a payment',
  BACK                       : 'Back',
  DAY                        : 'Day',
  ARE_YOU_SURE               : 'Are you sure?',
  NUMBER                     : '№',
  MONTHS_JAN                 : 'January',
  MONTHS_FEB                 : 'February',
  MONTHS_MAR                 : 'March',
  MONTHS_APR                 : 'April',
  MONTHS_MAY                 : 'May',
  MONTHS_JUN                 : 'June',
  MONTHS_JUL                 : 'July',
  MONTHS_AUG                 : 'August',
  MONTHS_SEP                 : 'September',
  MONTHS_OCT                 : 'October',
  MONTHS_NOV                 : 'November',
  MONTHS_DEC                 : 'December',
  LOGOUT                     : 'Logout',
  READY                      : 'Confirm',
  EDIT_PAYMENT               : 'Payment editing',
  SETTINGS                   : 'Settings',
  INCOME                     : 'Income',
  OUTCOME                    : 'Outcome',
  ADMINING                   : 'Admin panel',
  BACK_TO_HOME               : 'Back to home',
  USER                       : 'User',
  MONDAY                     : 'Mo',
  TUESDAY                    : 'Tu',
  WEDNESDAY                  : 'We',
  THURSDAY                   : 'Th',
  FRIDAY                     : 'Fr',
  SATURDAY                   : 'Sa',
  SUNDAY                     : 'Su',
  AUTHORIZATION              : 'Authorization',
  INPUT_USERNAME             : 'Input username',
  INPUT_PASSWORD             : 'Input password',
  USERNAME                   : 'Username',
  PASSWORD                   : 'Password',
  LOGIN                      : 'Login',
  SHOW_ALL_PAYMENTS          : 'Show payments from all users?',
  ADD_NEW_USER               : 'Add new user',
  USERS                      : 'Users',
  ROLE                       : 'Role',
  CONFIRM_DELETE_USER        : 'Are you sure you want to delete this user?',
  INPUT_NAME                 : 'Input name',
  ADD_NEW_PAYMENT_TYPE       : 'Add new payment type',
  PAYMENT_TYPES              : 'Payment types',
  ICON                       : 'Icon',
  PAYMENTS_AMOUNT            : 'Payments amount',
  NAME                       : 'Name',
  EXPORT_PAYMENTS            : 'Export payments',
  RELOAD_SESSIONS            : 'Reload active sessions',
  WILL_BE_REMOVED_PAYMENTS   : 'Will be removed payments',
  CONTINUE                   : 'Continue',
  ICON_SELECTING             : 'Icon selecting',
  INPUT_KEYWORD_TO_SEARCH    : 'Input any keyword to start search',
  CHANGE_PAYMENT_TYPE_NAME   : 'Change payment type name',
  ADD_NEW_PAYMENT_TYPE_NAME  : 'Input new payment type name',
  PAYMENT_TYPE               : 'Payment type',
  UPDATE                     : 'Update',
  USER_EDITING               : 'User editing',
  ADD_NEW_USERNAME           : 'Input new username',
  ADD_NEW_PASSWORD           : 'Input new password',
  SELECT_NEW_ROLE            : 'Select new user role',
  UPDATE_ROLE                : 'Update role',
  CHANGE_LANGUAGE            : 'Application language',
  SELECT_LANGUAGE            : 'Select language from the list',
  FOR_PAST_DATE              : 'Specify a specific date',
  MONTHS_SHORT_JAN           : 'Jan',
  MONTHS_SHORT_FEB           : 'Feb',
  MONTHS_SHORT_MAR           : 'Mar',
  MONTHS_SHORT_APR           : 'Apr',
  MONTHS_SHORT_MAY           : 'May',
  MONTHS_SHORT_JUN           : 'Jun',
  MONTHS_SHORT_JUL           : 'Jul',
  MONTHS_SHORT_AUG           : 'Aug',
  MONTHS_SHORT_SEP           : 'Sep',
  MONTHS_SHORT_OCT           : 'Oct',
  MONTHS_SHORT_NOV           : 'Nov',
  MONTHS_SHORT_DEC           : 'Dec',
  DAYS_MONDAY                : 'Monday',
  DAYS_TUESDAY               : 'Tuesday',
  DAYS_WEDNESDAY             : 'Wednesday',
  DAYS_THURSDAY              : 'Thursday',
  DAYS_FRIDAY                : 'Friday',
  DAYS_SATURDAY              : 'Saturday',
  DAYS_SUNDAY                : 'Sunday',
  DAYS_ABBR_MONDAY           : 'M',
  DAYS_ABBR_TUESDAY          : 'T',
  DAYS_ABBR_WEDNESDAY        : 'W',
  DAYS_ABBR_THURSDAY         : 'T',
  DAYS_ABBR_FRIDAY           : 'F',
  DAYS_ABBR_SATURDAY         : 'S',
  DAYS_ABBR_SUNDAY           : 'S',
  SPECIFY_DATE               : 'Specify date',
  // Backend messages
  'Invalid login or password': 'Invalid login or password',
  'Payment created'          : 'Payment successfully added',
  'Payment updated'          : 'Payment successfully updated',
  'Payment deleted'          : 'Payment removed',
  'Ptype created'            : 'New payment type successfully added',
  'Ptype updated'            : 'Payment type successfully updated',
  'Ptype deleted'            : 'Payment type removed',
  'User created'             : 'User successfully created',
  'User updated'             : 'User\'s settings updated',
  'User deleted'             : 'User deleted',
  'Ptype already exists'     : 'Payment type already exists',
  'Username already exists'  : 'Username already exists'
}
