export default {
  ADD_BUTTON                 : 'Добавить',
  DOCUMENT_TITLE             : 'Сервис Учёта',
  DOCUMENT_TITLE_HOME        : 'Главная страница',
  DOCUMENT_TITLE_DETAILS     : 'Детальная страница',
  DOCUMENT_TITLE_NOT_FOUND   : 'Не найдено',
  NOT_FOUND                  : '404 Страница не найдена',
  YES                        : 'Да',
  NO                         : 'Нет',
  CANCEL                     : 'Отмена',
  DATE                       : 'Дата',
  TIME                       : 'Время',
  TOTAL                      : 'Итого',
  TYPE                       : 'Тип операции',
  PAYMENT                    : 'Платёж',
  CONFIRM_DELETE             : 'Действительно удалить?',
  ACTIONS                    : 'Действия',
  SELECT_YEAR                : 'Выберите год',
  SELECT_MONTH               : 'Выберите месяц',
  INPUT_PAYMENT              : 'Введите оплату',
  ADD_PAYMENT                : 'Внести',
  MODAL_ADD_PAYMENT          : 'Добавить оплату',
  BACK                       : 'Назад',
  DAY                        : 'День',
  ARE_YOU_SURE               : 'Вы уверены?',
  NUMBER                     : '№',
  MONTHS_JAN                 : 'Январь',
  MONTHS_FEB                 : 'Февраль',
  MONTHS_MAR                 : 'Март',
  MONTHS_APR                 : 'Апрель',
  MONTHS_MAY                 : 'Май',
  MONTHS_JUN                 : 'Июнь',
  MONTHS_JUL                 : 'Июль',
  MONTHS_AUG                 : 'Август',
  MONTHS_SEP                 : 'Сентябрь',
  MONTHS_OCT                 : 'Октябрь',
  MONTHS_NOV                 : 'Ноябрь',
  MONTHS_DEC                 : 'Декабрь',
  LOGOUT                     : 'Выйти',
  READY                      : 'Готово',
  EDIT_PAYMENT               : 'Редактирование платежа',
  SETTINGS                   : 'Настройки',
  INCOME                     : 'Приход',
  OUTCOME                    : 'Расход',
  ADMINING                   : 'Администрирование',
  BACK_TO_HOME               : 'На главную',
  USER                       : 'Пользователь',
  MONDAY                     : 'Пн',
  TUESDAY                    : 'Вт',
  WEDNESDAY                  : 'Ср',
  THURSDAY                   : 'Чт',
  FRIDAY                     : 'Пт',
  SATURDAY                   : 'Сб',
  SUNDAY                     : 'Вск',
  AUTHORIZATION              : 'Авторизация',
  INPUT_USERNAME             : 'Введите имя пользователя',
  INPUT_PASSWORD             : 'Введите пароль',
  USERNAME                   : 'Имя пользователя',
  PASSWORD                   : 'Пароль',
  LOGIN                      : 'Войти',
  SHOW_ALL_PAYMENTS          : 'Показывать платежи от всех пользователей?',
  ADD_NEW_USER               : 'Добавить нового пользователя',
  USERS                      : 'Пользователи',
  ROLE                       : 'Роль',
  CONFIRM_DELETE_USER        : 'Вы уверены, что хотите удалить данного пользователя?',
  INPUT_NAME                 : 'Введите название',
  ADD_NEW_PAYMENT_TYPE       : 'Добавить новый тип платежа',
  PAYMENT_TYPES              : 'Типы платежей',
  ICON                       : 'Иконка',
  PAYMENTS_AMOUNT            : 'Количество платежей',
  NAME                       : 'Название',
  EXPORT_PAYMENTS            : 'Экспортировать платежи',
  RELOAD_SESSIONS            : 'Перезагрузить активные сессии',
  WILL_BE_REMOVED_PAYMENTS   : 'Будет удалено платежей',
  CONTINUE                   : 'Продолжить',
  ICON_SELECTING             : 'Выбор иконки',
  INPUT_KEYWORD_TO_SEARCH    : 'Введите ключевое слово для поиска',
  CHANGE_PAYMENT_TYPE_NAME   : 'Изменить наименование платежей',
  ADD_NEW_PAYMENT_TYPE_NAME  : 'Введите новое название платежей',
  PAYMENT_TYPE               : 'Тип платежа',
  UPDATE                     : 'Изменить',
  USER_EDITING               : 'Редактирование данных пользователя',
  ADD_NEW_USERNAME           : 'Введите новое имя пользователя',
  ADD_NEW_PASSWORD           : 'Введите новый пароль',
  SELECT_NEW_ROLE            : 'Выберите новую роль пользователя',
  UPDATE_ROLE                : 'Изменить роль',
  CHANGE_LANGUAGE            : 'Язык приложения',
  SELECT_LANGUAGE            : 'Выберите язык из списка',
  FOR_PAST_DATE              : 'Указать определенную дату',
  MONTHS_SHORT_JAN           : 'Янв',
  MONTHS_SHORT_FEB           : 'Фев',
  MONTHS_SHORT_MAR           : 'Мар',
  MONTHS_SHORT_APR           : 'Апр',
  MONTHS_SHORT_MAY           : 'Май',
  MONTHS_SHORT_JUN           : 'Июн',
  MONTHS_SHORT_JUL           : 'Июл',
  MONTHS_SHORT_AUG           : 'Авг',
  MONTHS_SHORT_SEP           : 'Сен',
  MONTHS_SHORT_OCT           : 'Окт',
  MONTHS_SHORT_NOV           : 'Ноя',
  MONTHS_SHORT_DEC           : 'Дек',
  DAYS_MONDAY                : 'Понедельник',
  DAYS_TUESDAY               : 'Вторник',
  DAYS_WEDNESDAY             : 'Среда',
  DAYS_THURSDAY              : 'Четверг',
  DAYS_FRIDAY                : 'Пятница',
  DAYS_SATURDAY              : 'Суббота',
  DAYS_SUNDAY                : 'Воскресенье',
  DAYS_ABBR_MONDAY           : 'П',
  DAYS_ABBR_TUESDAY          : 'В',
  DAYS_ABBR_WEDNESDAY        : 'С',
  DAYS_ABBR_THURSDAY         : 'Ч',
  DAYS_ABBR_FRIDAY           : 'П',
  DAYS_ABBR_SATURDAY         : 'С',
  DAYS_ABBR_SUNDAY           : 'В',
  SPECIFY_DATE               : 'Указать дату',
  // Backend messages
  'Invalid login or password': 'Неверный логин или пароль',
  'Payment created'          : 'Платеж успешно добавлен',
  'Payment updated'          : 'Платеж успешно обновлен',
  'Payment deleted'          : 'Платеж удален',
  'Ptype created'            : 'Новый тип платежа успешно добавлен',
  'Ptype updated'            : 'Тип платежа успешно изменен',
  'Ptype deleted'            : 'Тип платежа удален',
  'User created'             : 'Пользователь успешно создан',
  'User updated'             : 'Настройки пользователя успешно изменены',
  'User deleted'             : 'Пользователь удален',
  'Ptype already exists'     : 'Такой тип платежа уже существует',
  'Username already exists'  : 'Такое имя пользователя уже занято'
}
