export default {
  ADD_BUTTON: 'Добавить',
  DOCUMENT_TITLE: 'Сервис Учёта',
  DOCUMENT_TITLE_HOME: 'Главная страница',
  DOCUMENT_TITLE_DETAILS: 'Детальная страница',
  DOCUMENT_TITLE_NOT_FOUND: 'Не найдено',
  NOT_FOUND: '404 Страница не найдена',
  YES: 'Да',
  CANCEL: 'Отмена',
  DATE: 'Дата',
  TIME: 'Время',
  CASH: 'Наличный расчёт',
  BANK: 'Безналичный расчёт',
  CARD: 'Оплата по карте',
  KASPI: 'Оплата на Kaspi Gold',
  TOTAL: 'Итого',
  TOTAL_MONTH: 'Всего за месяц',
  TYPE: 'Тип операции',
  PAYMENT: 'Платёж',
  CONFIRM_DELETE: 'Действительно удалить?',
  ACTIONS: 'Действия',
  SELECT_YEAR: 'Выберите год',
  SELECT_MONTH: 'Выберите месяц',
  INPUT_PAYMENT: 'Введите оплату',
  ADD_PAYMENT: 'Внести',
  MODAL_ADD_PAYMENT: 'Добавить оплату',
  BACK: 'Назад',
  DAY: 'День',
  ARE_YOU_SURE: 'Вы уверены?',
  NUMBER: '№',
  MONTHS_JAN: 'Январь',
  MONTHS_FEB: 'Февраль',
  MONTHS_MAR: 'Март',
  MONTHS_APR: 'Апрель',
  MONTHS_MAY: 'Май',
  MONTHS_JUN: 'Июнь',
  MONTHS_JUL: 'Июль',
  MONTHS_AUG: 'Август',
  MONTHS_SEP: 'Сентябрь',
  MONTHS_OCT: 'Октябрь',
  MONTHS_NOV: 'Ноябрь',
  MONTHS_DEC: 'Декабрь',
  LOGOUT: 'Выйти',
  READY: 'Готово',
  EDIT_PAYMENT: 'Редактирование платежа',
  SETTINGS: 'Настройки',
  INCOME: 'Приход',
  OUTCOME: 'Расход',
  ADMINING: 'Администрирование',
  BACK_TO_HOME: 'На главную',
  NEED_RELOAD: 'Администратор сайта внёс изменения в работу сайта, страница будет перезагружена.',
  USER: 'Пользователь',
  MONDAY: 'пн.',
  TUESDAY: 'вт.',
  WEDNESDAY: 'ср.',
  THURSDAY: 'чт.',
  FRIDAY: 'пт.',
  SATURDAY: 'сб.',
  SUNDAY: 'вск.',
  // Backend messages
  'Invalid login or password': 'Неверный логин или пароль'
}
